import { MessageSquareDot, Play, Star, ChevronLeft, ChevronRight } from "lucide-react";
import { motion } from "motion/react";
import { Testimonial } from "../types";

interface TestimonialsProps {
  onPlayReview: (title: string) => void;
}

const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    quote: "The research translation print and audio briefs generated by IPIC Africa completely revolutionized how our national assembly interpreted regional health data.",
    authorName: "Dr. Catherine Appiah",
    authorRole: "Deputy Director, health Ministry",
    category: "Research Translation",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "test-2",
    quote: "Their inclusive design approach and workshops paved the way for robust civic transparency and rights-based artificial intelligence policy in West Africa.",
    authorName: "Kofi Owusu",
    authorRole: "Executive Secretary, Civic Digital Forum",
    category: "Governance & Tech Policy",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=800",
  },
];

export default function Testimonials({ onPlayReview }: TestimonialsProps) {
  return (
    <section className="bg-brand-cream py-16 sm:py-24 border-b border-brand-green/5">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12">
          <div>
            <div className="flex items-center space-x-2 text-brand-green mb-3">
              <MessageSquareDot className="h-5 w-5 text-brand-gold fill-brand-gold animate-bounce" />
              <span className="font-display text-xs font-extrabold uppercase tracking-widest text-brand-green">
                Stakeholder Testimonials
              </span>
            </div>
            <h2 className="font-display text-3xl font-extrabold tracking-tight text-brand-charcoal sm:text-4xl md:text-5xl leading-tight">
              Why They Partner With Us
            </h2>
          </div>

          {/* Action Row right */}
          <div className="mt-4 md:mt-0 flex items-center space-x-3">
            <button
              onClick={() => onPlayReview("IPIC Africa Regional Partner Success Documentary")}
              className="group flex items-center space-x-2 rounded-full bg-brand-green hover:bg-brand-gold px-6 py-3.5 text-sm font-bold text-white hover:text-brand-charcoal transition-all duration-300 shadow-md cursor-pointer"
            >
              <span>View Partner Insights</span>
            </button>
          </div>
        </div>

        {/* Testimonials Video Columns */}
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
          {TESTIMONIALS.map((t) => (
            <motion.div
              key={t.id}
              initial={{ opacity: 0, y: 25 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="relative rounded-3xl overflow-hidden aspect-[4/3] shadow-md group border border-gray-100 bg-brand-charcoal"
            >
              {/* Image backdrop click opens review play */}
              <div
                className="absolute inset-0 cursor-pointer"
                onClick={() => onPlayReview(`Stakeholder Video Log: ${t.authorName} on ${t.category}`)}
              >
                <div className="absolute inset-0 bg-gradient-to-t from-brand-charcoal/95 via-brand-charcoal/40 to-transparent z-10" />
                <img
                  src={t.image}
                  alt={t.authorName}
                  referrerPolicy="no-referrer"
                  className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"
                />

                {/* Overlaid Pulsating Play Button */}
                <div className="absolute inset-0 flex items-center justify-center z-20">
                  <div className="flex h-14 w-14 items-center justify-center rounded-full bg-white/90 text-brand-green hover:bg-brand-gold hover:text-brand-charcoal hover:scale-110 shadow-lg cursor-pointer transition-all duration-300">
                    <Play className="h-6 w-6 fill-current translate-x-0.5" />
                  </div>
                </div>

                {/* Overlaid Comment Content Card */}
                <div className="absolute bottom-4 left-4 right-4 z-20 rounded-2xl bg-white p-5 text-brand-charcoal shadow-xl border border-gray-100">
                  <div className="flex items-center justify-between mb-3">
                    <span className="rounded-full bg-brand-light-green px-3 py-1 font-mono text-[10px] font-extrabold uppercase text-brand-green">
                      {t.category}
                    </span>
                    <div className="flex text-brand-gold">
                      {Array.from({ length: 5 }).map((_, i) => (
                        <Star key={i} className="h-3.5 w-3.5 fill-current" />
                      ))}
                    </div>
                  </div>

                  <p className="text-xs text-gray-500 italic leading-relaxed font-semibold mb-4">
                    "{t.quote}"
                  </p>

                  <div className="flex items-center space-x-3 border-t border-gray-100 pt-3">
                    <div className="text-left">
                      <h4 className="text-xs font-bold text-brand-charcoal leading-none">
                        {t.authorName}
                      </h4>
                      <span className="text-[10px] text-gray-400 font-semibold tracking-wider">
                        {t.authorRole}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
        
      </div>
    </section>
  );
}
